INSERT INTO branch VALUES
(null,"Via Flaminia",87,"Ρώμη"),
(null,"Via Leone Magno",2,"Ρώμη"),
(null,"Via della Moletta",17,"Ρώμη"),
(null,"Via Salvatore Talamo",26,"Ρώμη"),
(null,"Via Arbe",3,"Μιλάνο"),
(null,"Via Vignola",41,"Μιλάνο"),
(null,"Via Duomo",38,"Νάπολη"),
(null,"Via Luigi Volpicella",21,"Νάπολη"),
(null,"Via Vittorio Alfieri",8,"Τουρίνο"),
(null,"Via Umberto Giordano",51,"Παλέρμο"),
(null,"Via S. Benedetto",107,"Γένοβα"),
(null,"Via S. Vitale",37,"Μπολώνια"),
(null,"Via S. Zanobi",47,"Φλωρεντία"),
(null,"Via Case Sante",83,"Κατάνια"),
(null,"Via Matteo Renato Imbriani",9,"Μπάρι"),
(null,"Via dei Verdi",62,"Μεσσήνη"),
(null,"Via Pallone",59,"Βερόνα"),
(null,"Via delle Palme",15,"Πάντοβα"),
(null,"Via Enrico Toti",21,"Τεργέστη"),
(null,"Via Gezio Calini",65,"Μπρέσια"),
(null,"Via Sant'Jacopo",31,"Πράτο"),
(null,"Via Francesco Paolo Parisi",16,"Τάραντας"),
(null,"Via Emilia Ovest",33,"Μόντενα"),
(null,"Via Serristori",15,"Λιβόρνο"),
(null,"Via Giardini",29,"Κάλιαρι"),
(null,"Via Sernaglia",11,"Μέστρε"),
(null,"Via Ferdinando Maestri",12,"Πάρμα"),
(null,"Via Zodiaco",26,"Φότζια"),
(null,"Via Volontari della Liberta",14,"Σαλέρνο"),
(null,"Via del Cantone",1,"Περούτζια");
