/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;
import java.sql.*;

/**
 *
 * @author antonis
 */
public class LoginFrame extends javax.swing.JFrame {
    
    private static final String DB_URL = ("jdbc:mysql://localhost:3306/travel_agency");

    /**
     * Creates new form NewJFrame
     */
    public LoginFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        username_login_field = new javax.swing.JTextField();
        login_button = new javax.swing.JButton();
        password_login_field = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        username_login_field.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        username_login_field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                username_login_fieldActionPerformed(evt);
            }
        });

        login_button.setText("Login");
        login_button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                login_buttonMouseClicked(evt);
            }
        });
        login_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                login_buttonActionPerformed(evt);
            }
        });

        password_login_field.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        password_login_field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                password_login_fieldActionPerformed(evt);
            }
        });

        jLabel1.setText("Enter Password");

        jLabel2.setText("Enter Username");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(152, 152, 152)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(password_login_field)
                    .addComponent(username_login_field)
                    .addComponent(login_button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(167, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(username_login_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(password_login_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addComponent(login_button)
                .addGap(19, 19, 19))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void username_login_fieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_username_login_fieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_username_login_fieldActionPerformed

    private void login_buttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_login_buttonMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_login_buttonMouseClicked

    private void login_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_login_buttonActionPerformed
        String username=username_login_field.getText();
        String password=password_login_field.getText();
        
        try{
            Connection con = DriverManager.getConnection(DB_URL,"root","1234");

            // Initialize a statement object for executing queries to database
            Statement stmtU = con.createStatement();
            ResultSet getUsernames = stmtU.executeQuery("SELECT wrk_AT,wrk_lname FROM worker INNER JOIN it ON it_at=wrk_AT");

            
            String saveAT="";
            boolean existsU = false;
            boolean existsP = false;
                    
                    while(getUsernames.next()){
                            String usr  = getUsernames.getString("wrk_lname");
                            String usrAT = getUsernames.getString("wrk_AT");

                            if(usr.equals(username)){
                                existsU = true;
                                saveAT = usrAT;
                                break;
                            }                
                    }        
                    

                    Statement stmtP = con.createStatement();
                    ResultSet getPasswords = stmtP.executeQuery("SELECT it_at,passwords FROM it INNER JOIN worker ON it_at=wrk_AT");
                    
                    
                    while(getPasswords.next()){
                        String psw = getPasswords.getString("passwords");
                        String at = getPasswords.getString("it_at");

                        if(psw.equals(password) && saveAT.equals(at)) {
                                existsP = true;
                                break;
                        }
                    }

                    if(existsU && existsP){
                        System.out.println("Logged in");

                    }else{
                        System.out.println("Wrong user");
                    }

        }catch(SQLException ex){
                    ex.printStackTrace();
        }
        
        
        
    }//GEN-LAST:event_login_buttonActionPerformed

    private void password_login_fieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_password_login_fieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_password_login_fieldActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton login_button;
    private javax.swing.JPasswordField password_login_field;
    private javax.swing.JTextField username_login_field;
    // End of variables declaration//GEN-END:variables
}
